<a href="https://colab.research.google.com/github/thaiyalvishu97/MyProjects/blob/main/Project_31.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Project 31 - obesity classification

In [9]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [10]:
df = pd.read_csv("Obesity Classification.csv")

In [11]:
df.isnull().sum()

ID        0
Age       0
Gender    0
Height    0
Weight    0
BMI       0
Label     0
dtype: int64

In [12]:
df

      ID  Age  Gender  Height  Weight   BMI          Label
0      1   25    Male     175      80  25.3  Normal Weight
1      2   30  Female     160      60  22.5  Normal Weight
2      3   35    Male     180      90  27.3     Overweight
3      4   40  Female     150      50  20.0    Underweight
4      5   45    Male     190     100  31.2          Obese
..   ...  ...     ...     ...     ...   ...            ...
103  106   11    Male     175      10   3.9    Underweight
104  107   16  Female     160      10   3.9    Underweight
105  108   21    Male     180      15   5.6    Underweight
106  109   26  Female     150      15   5.6    Underweight
107  110   31    Male     190      20   8.3    Underweight

[108 rows x 7 columns]

In [13]:
le = LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df['Label']=le.fit_transform(df['Label'])
df

      ID  Age  Gender  Height  Weight   BMI  Label
0      1   25       1     175      80  25.3      0
1      2   30       0     160      60  22.5      0
2      3   35       1     180      90  27.3      2
3      4   40       0     150      50  20.0      3
4      5   45       1     190     100  31.2      1
..   ...  ...     ...     ...     ...   ...    ...
103  106   11       1     175      10   3.9      3
104  107   16       0     160      10   3.9      3
105  108   21       1     180      15   5.6      3
106  109   26       0     150      15   5.6      3
107  110   31       1     190      20   8.3      3

[108 rows x 7 columns]

In [14]:
X = df.drop(columns='Label',axis=1)
Y = df['Label']
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=42)

In [15]:
model= LogisticRegression()
model.fit(X_train,Y_train)
X_train_predict = model.predict(X_train)
print("Accuracy on training data:",accuracy_score(X_train_predict,Y_train))
X_test_predict = model.predict(X_test)
print("Accuracy on testing data:",accuracy_score(X_test_predict,Y_test))

Accuracy on training data: 0.872093023255814
Accuracy on testing data: 0.8181818181818182

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [16]:
input_data = (4,40,0,150,50,20.0)
input_data_as_num_array = np.asarray(input_data)
input_data_array_reshaped = input_data_as_num_array.reshape(1,-1)
prediction = model.predict(input_data_array_reshaped)
if prediction[0] == 0:
  print("Normal Weight")
elif prediction[0] == 1:
  print("Underweight")
elif prediction[0] == 2:
  print("Overweight")
elif prediction[0] == 3:
  print("Underweight")

Underweight

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(